### ISSUE TITLE
do not store .exe in repo, use releases instead

### ISSUE THREAD

**Issue by steren** [maranone/AlyxLauncher#1]
The git repo should be used to store the source code of the executable, not the executable itself.

the .exe itself should rather be distributed using GitHub's "release" feature, where users can download the compiled source.

**Comment by steren** [comment]
Ah sorry I realize the soruce is at https://github.com/maranone/AlyxLauncher-2

I recommend using only one repo, with the source in git and the .exe in Releases.

**Comment by maranone** [comment]
Sorry I have not checked the releases. I have deleted the files and will try to do properly from the source instead. Regards.
